# $FreeBSD$

PORTNAME=	scientific
PORTVERSION=	0.2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Numbers represented using scientific notation

LICENSE=	BSD

USE_CABAL=	hashable>=1.1.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
