# $FreeBSD$

PORTNAME=	containers
PORTVERSION=	0.5.5.1
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Assorted concrete container types

LICENSE=	BSD

USE_CABAL=	array deepseq>=1.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
