# $FreeBSD$

PORTNAME=	bytestring
PORTVERSION=	0.10.4.0
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Fast, compact, strict and lazy byte strings with a list interface

LICENSE=	BSD

USE_CABAL=	deepseq

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
