# $FreeBSD$

PORTNAME=	array
PORTVERSION=	0.5.0.0
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Mutable and immutable arrays

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
