# $FreeBSD$

PORTNAME=	old-locale
PORTVERSION=	1.0.0.6
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	locale library

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
