# $FreeBSD$

PORTNAME=	unix
PORTVERSION=	2.7.0.1
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	POSIX functionality

LICENSE=	BSD

USE_CABAL=	time>=1.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
