# $FreeBSD$

PORTNAME=	time
PORTVERSION=	1.4.2
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	A time library

LICENSE=	BSD

USE_CABAL=	deepseq>=1.1 old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
